---
- name: Test of ROLE 
  hosts: servera.lab.example.com
  gather_facts: no
  tasks:
    - name: Postfix is installed and updated
      yum: name=postfix state=latest
      notify: restart_postfix

    - name: Postfix is running
      service: name=postfix state=started


#    - name: Postfix is installed and updated
#      yum: 
#        name: postfix
#        state: latest
#      notify: restart_postfix
#
#    - name: Postfix is running
#      service: 
#        name: postfix
#        state: started

  handlers:
    - name: restart_postfix
      service:
        name: postfix
        state: restarted
          
