--- 
- name: Delegate fact example
  hosts: serverb.lab.example.com
  tasks:
    - name: Set a fact in delegated task on servera
      set_fact:
        myfact: Where am I set?
      delegate_to: servera.lab.example.com
      delegate_facts: True

    - name: Display the facts from servera.lab.example.com
      debug:
        msg: "{{ hostvars['servera.lab.example.com']['myfact'] }}"
