---
- name: Learning Order of execution
  hosts: servera.lab.example.com
  gather_facts: no
  tasks:
    - name: Install HTTPD service 
      yum:
        name: httpd
        state: present
  
  roles:
    - role: vsftpd

#Ansible runs the ROLE tasks before the regular tasks mentioned below tasks section#
