---
- name: Including Role as a task
  hosts: servera.lab.example.com
  gather_facts: no
  pre_tasks:
    - name: This is pre task
      debug:
        msg: "Deploying FTP Server......"
  roles:
    - role: vsftpd

  tasks:
    - name: Checking if FTP deployment was OK
      wait_for:
        host: servera.lab.example.com
        port: 21
        timeout: 1
      register: output
    - name: Displaying Result
      debug:
        var=output
  
  post_tasks:
    - name: This is post task
      debug:
        msg: "FTP Server is up and running"

